services:
  eliza:
    command:
    - pnpm
    - start
    - --character=./characters/e3babd31-853f-43b1-8fb0-df51ac807193.character.json
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
    - ./data:/app/data
    - ./characters:/app/characters
    environment:
    - GOOGLE_GENERATIVE_AI_API_KEY=AIzaSyCTL22xpBFNXfyz13zn6dEPqc3tpWDttbI
    - GROQ_API_KEY=
    - TWITTER_DRY_RUN=false
    - TWITTER_USERNAME=chillguy0980
    - TWITTER_PASSWORD=Vikas@ant30
    - TWITTER_EMAIL=vikas.adhikari@antiersolutions.com
    - POST_INTERVAL_MIN=1
    - POST_INTERVAL_MAX=3
    - OPENROUTER_API_KEY=
    - ELEVENLABS_XI_API_KEY=
    - ELEVENLABS_MODEL_ID=eleven_multilingual_v2
    - ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
    - ELEVENLABS_VOICE_STABILITY=0.5
    - ELEVENLABS_VOICE_SIMILARITY_BOOST=0.9
    - ELEVENLABS_VOICE_STYLE=0.66
    - ELEVENLABS_VOICE_USE_SPEAKER_BOOST=false
    - ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=4
    - ELEVENLABS_OUTPUT_FORMAT=pcm_16000
    - SOL_ADDRESS=So11111111111111111111111111111111111111112
    - SLIPPAGE=1
    - SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
    - HELIUS_API_KEY=
    - SERVER_PORT=3000
    ports:
    - 3000:3000
    restart: always
